version: '3.8'

services:
  web:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    env_file:
      - .env.docker
    networks:
      - my_act_network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my_act_network

networks:
  my_act_network:
    external: true
